version: '3.9'
services:
  account-server:
    build:
      dockerfile: ./docker/account-server/Dockerfile
      context: .
    ports:
      - "8080:8080"
    extra_hosts:
      - "database:10.0.0.58"
